### ISSUE TITLE
App unable to locate 'libnut.node' 'Error: The specified module could not be found.'

### ISSUE THREAD

**Issue by c-ridgway** [nut-tree/libnut#70]
**Version**
2.1.1

**Detailed error description**

I'm unable to launch my application due to the following error:
```
Error: The specified module could not be found.                                                                         
\\?\C:\Users\ropw\Desktop\autorestart\node_modules\@nut-tree\libnut-win32\build\Release\libnut.node                     
←[90m    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)←[39m                               
←[90m    at Module.load (internal/modules/cjs/loader.js:933:32)←[39m                                                    
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:774:14)←[39m                                          
←[90m    at Module.require (internal/modules/cjs/loader.js:957:19)←[39m                                                 
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m                                                            at bindings (C:\Users\ropw\Desktop\autorestart\node_modules\←[4mbindings←[24m\bindings.js:112:48)                       at Object.<anonymous> (C:\Users\ropw\Desktop\autorestart\node_modules\←[4m@nut-tree←[24m\libnut-win32\index.js:1:35)                                                                                                                        ←[90m    at Module._compile (internal/modules/cjs/loader.js:1068:30)←[39m                                               
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)←[39m                                 
←[90m    at Module.load (internal/modules/cjs/loader.js:933:32)←[39m 
```

**Additional content**
My package.json:
```
{
  "dependencies": {
    "@nut-tree/libnut": "^2.1.1",
    "@nut-tree/nut-js": "^1.6.0",
    "mocha": "^8.4.0",
    "tasklist": "^4.0.1",
    "window-control": "^1.4.4"
  },
  "bin": "bin.js",
  "name": "app"
}
```

The file seems to exist:
![image](https://user-images.githubusercontent.com/74696795/118965381-c11fa980-b9bc-11eb-8ee2-db9c24379fa2.png)

**Comment by rapsealk** [comment]
Hi. I have the very same symptom.
Do you have Microsoft Visual C++ Redistributional installed on your machine?
If you found how to fix it, please share it with us.
Thank you.
